POST http://localhost:4000/api/contact
Content-Type: application/json

{   
    "firstname": "Adewale",
    "lastname": "Philemon",
    "email": "wale@test.com",
    "number": "08115861199",
    "need": "i'm currently in need of a website and a mobile app, let's discuss"
}